// motelDescriptors.js
module.exports.descriptors = [
    'Cozy',
    'Modern',
    'Tranquil',
    'Urban',
    'Sunny',
    'Rustic',
    'Charming',
    'Luxurious',
    'Elegant',
    'Vintage',
    'Seaside',
    'Quaint',
    'Relaxing',
    'Romantic',
    'Sleek',
    'Minimalist',
    'Mountain View',
    'Cityscape',
    'Lakeside',
    'Trendy',
    'Contemporary',
];

// motelPlaces.js
module.exports.places = [
    'Inn',
    'Lodge',
    'Retreat',
    'Suites',
    'Residence',
    'Manor',
    'Oasis',
    'Court',
    'Harbor',
    'Haven',
    'Vista',
    'Loft',
    'Terrace',
    'Nest',
    'Paradise',
    'Hideaway',
    'Gardens',
    'Plaza',
    'Quarters',
    'Village',
    'Penthouse',
];
